# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pilotSolve <- function(Y_r, X_r, B_r, C_r, tol_r, Max_r, rank_r) {
    .Call(`_MVCM_binary_pilotSolve`, Y_r, X_r, B_r, C_r, tol_r, Max_r, rank_r)
}

rcpparma_hello_world <- function() {
    .Call(`_MVCM_binary_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_MVCM_binary_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_MVCM_binary_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_MVCM_binary_rcpparma_bothproducts`, x)
}

updateA <- function(Y_r, X_r, Theta_r, B_r, A_r, tol_r, Max_r, subMax_r, beta_r, alpha_r, sigma_r) {
    .Call(`_MVCM_binary_updateA`, Y_r, X_r, Theta_r, B_r, A_r, tol_r, Max_r, subMax_r, beta_r, alpha_r, sigma_r)
}

update_Theta <- function(Theta_r, Y_r, X_r, B_r, A_r, lambda_r, tol_r, MaxIt_r, tau_r, m_r, method_r, a_r) {
    .Call(`_MVCM_binary_update_Theta`, Theta_r, Y_r, X_r, B_r, A_r, lambda_r, tol_r, MaxIt_r, tau_r, m_r, method_r, a_r)
}

